# Generated by Django 4.2.6 on 2023-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
