# Generated by Django 4.2.6 on 2023-12-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0002_post_decline_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posting_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
