from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path("activity", views.map, name='activity'),
    path('logout', views.logout_view, name='logout'),
    path('create_post/', views.add_wildlife_post, name='add_wildlife_and_post'),
    path("add_entry/", views.add_entry, name="add_entry"),
    path("activity", views.map, name='activity'),
    path("activity/<int:post_id>/save", views.save, name='save'),
    path("activity/<int:post_id>/unsave", views.unsave, name='unsave'),
    path('mydata',views.mydata, name="mydata"),
    path('map', views.map, name="map"),
    path('user_map', views.users_map, name = "user_map"),
    path("<int:post_id>/<int:wildlife_id>/user_map_handle_post/", views.user_map_handle_post, name="user_map_handle_post"),
    path("<int:post_id>/<int:wildlife_id>/user_map_handle_post/post_detail/", views.post_detail, name='post_detail'),
    path('<int:post_id>/<str:action>/react/', views.react, name='react'),
    path('approval_portal',views.approval_portal, name="approval_portal"),
    path('<int:post_id>/approve_post/', views.approve_post, name='approve_post'),
    path('<int:post_id>/decline_post/', views.decline_post, name='decline_post'),
    path('all_posts', views.all_posts, name="all_posts"),
    path("<int:post_id>/<int:wildlife_id>/handle_all_posts/post_detail/", views.post_detail, name='post_detail'),
    path("<int:post_id>/<int:wildlife_id>/handle_all_posts/", views.handle_post, name="handle_all_posts"),
    path("<int:post_id>/<int:wildlife_id>/handle_post/post_detail/", views.post_detail, name='post_detail'),
    path("<int:post_id>/<int:wildlife_id>/handle_post/", views.handle_post, name="handle_post"),
    path("<int:post_id>/<int:wildlife_id>/handle_post/save", views.save, name="save"),
    path("<int:post_id>/<int:wildlife_id>/handle_post/unsave", views.unsave, name="unsave"),
    path('saved_map/', views.saved_map, name="saved_map"),
    path("<int:post_id>/<int:wildlife_id>/handle_saved_post/", views.handle_saved_post, name="handle_saved_post"),
    path("<int:post_id>/<int:wildlife_id>/handle_saved_post/post_detail/", views.post_detail, name="post_detail"),
    path('save_post/<int:post_id>/<int:wildlife_id>/', views.save_post, name='save_post'),
    path('accounts/', include('allauth.urls')),
]